resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/JassoftLtd/DashVid-Uploader.git
    branch: master

- name: gh-release
  type: github-release
  source:
    user: JassoftLtd
    repository: DashVid-Uploader
    access_token: {{gh_access_token}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack_webhook_url}}

jobs:
- name: DashVid-Uploader
  plan:
  - get: source-code
    trigger: true

  - task: Build
    privileged: true
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind

      inputs:
      - name: source-code

      outputs:
      - name: artifact

      run:
        path: sh
        args:
        - -exc
        - |
          source /docker-lib.sh
          start_docker
          cd source-code
          docker run -v $(pwd)/DashVid:/src centurylink/golang-builder-cross
          ls -ltrh DashVid
          mkdir ../artifact/bin
          cp DashVid/DashVid-Uploader* ../artifact/bin
          echo "name" > ../artifact/name
          echo "tag" > ../artifact/tag
          echo "body" > ../artifact/body
    on_failure:
      put: slack-alert
      params:
        channel: '#build-notifications'
        text: |
          Build Failed. Check it out at:
          http://concourse.jassoft.co.uk:8080/builds/$BUILD_ID

  - put: gh-release
    inputs:
    - name: artifact
    params:
      name: artifact/name
      tag: artifact/tag
      body: artifact/body
      globs:
      - artifact/bin/*

  - put: slack-alert
    params:
      channel: '#build-notifications'
      text: |
        Production Deployment Successful. Check it out at:
        http://concourse.jassoft.co.uk:8080/builds/$BUILD_ID