resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/JassoftLtd/DashVid-Uploader.git
    branch: master

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:JassoftLtd/DashVid-Uploader.git
    branch: version
    file: version
    private_key: {{concourse-repo-private-key}}

- name: gh-release
  type: github-release
  source:
    user: JassoftLtd
    repository: DashVid-Uploader
    access_token: {{gh_access_token}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack_webhook_url}}

jobs:
- name: DashVid-Uploader
  plan:
  - get: source-code
    trigger: true
  - get: version
    params: {bump: minor}

  - task: Build
    privileged: true
    config:
      platform: linux

      image_resource:
        type: docker-image
        source:
          repository: amidos/dcind

      inputs:
      - name: source-code

      outputs:
      - name: artifact

      run:
        path: sh
        args:
        - -exc
        - |
          source /docker-lib.sh
          start_docker
          cd source-code
          docker run -v $(pwd)/DashVid:/src centurylink/golang-builder-cross
          ls -ltrh DashVid
          mkdir ../artifact/bin
          cp DashVid/DashVid-Uploader* ../artifact/bin
    on_failure:
      put: slack-alert
      params:
        channel: '#build-notifications'
        text: |
          Build Failed. Check it out at:
          http://concourse.jassoft.co.uk:8080/builds/$BUILD_ID

  - put: gh-release
    inputs:
    - name: artifact
    params:
      name: version/version
      tag: version/version
      globs:
      - artifact/bin/*

  - put: version
    params: {file: version/version}

  - put: slack-alert
    params:
      channel: '#build-notifications'
      text: |
        DashVid Uploader Deployment Successful. Check it out at:
        http://concourse.jassoft.co.uk:8080/builds/$BUILD_ID